### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by nsobiratel** [ComparetheMarket/fettle#24]
I try run fettle on unity3d testproject (based on nunit) and unity plugin. 
fettle 0.1.0 from nuget

Analysing test coverageAn error ocurred that Fettle didn't expect.
System.AggregateException: Произошла одна или несколько ошибок. ---> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Fettle.Core.CoverageAnalyser.InstrumentMethod(String methodId, MethodDeclarationSyntax methodNode, DocumentEditor documentEditor) в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 197
   в Fettle.Core.CoverageAnalyser.<InstrumentDocument>d__9.MoveNext() в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 167
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Fettle.Core.CoverageAnalyser.<InstrumentThenCompileProject>d__8.MoveNext() в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 128
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Fettle.Core.CoverageAnalyser.<InstrumentThenCompileMultipleProjects>d__7.MoveNext() в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 103
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Fettle.Core.CoverageAnalyser.<AnalyseMethodCoverage>d__6.MoveNext() в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 53
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   в System.Threading.Tasks.Task`1.get_Result()
   в Fettle.Console.Program.AnalyseCoverage(ICoverageAnalyser coverageAnalyser, IOutputWriter outputWriter, Config config) в c:\dev\fettle\src\Console\Program.cs:строка 113
   в Fettle.Console.Program.InternalEntryPoint(String[] args, Func`3 mutationTestRunnerFactory, Func`2 coverageAnalyserFactory, IOutputWriter outputWriter) в c:\dev\fettle\src\Console\Program.cs:строка 57
---> (Внутреннее исключение #0) System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Fettle.Core.CoverageAnalyser.InstrumentMethod(String methodId, MethodDeclarationSyntax methodNode, DocumentEditor documentEditor) в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 197
   в Fettle.Core.CoverageAnalyser.<InstrumentDocument>d__9.MoveNext() в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 167
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Fettle.Core.CoverageAnalyser.<InstrumentThenCompileProject>d__8.MoveNext() в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 128
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Fettle.Core.CoverageAnalyser.<InstrumentThenCompileMultipleProjects>d__7.MoveNext() в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 103
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Fettle.Core.CoverageAnalyser.<AnalyseMethodCoverage>d__6.MoveNext() в c:\dev\fettle\src\Core\CoverageAnalyser.cs:строка 53<---

**Comment by oliwennell** [comment]
Thanks for the report @nsobiratel , I will look into this soon.

**Comment by oliwennell** [comment]
From looking at the stack trace, it seems that Fettle is expecting a method declaration to have a body, but it doesn't. I'm thinking this might be a `partial` method, which Fettle doesn't handle correctly yet.

Does the code you're running Fettle against contain partial methods @nsobiratel ?

**Comment by oliwennell** [comment]
I've raised #25 for not handling empty partial method declarations

**Comment by nsobiratel** [comment]
yes, project contains two partial class

**Comment by nsobiratel** [comment]
i think trouble in second case in specific type of unity3d tests (they have returned type IEnumerator, attribute UnityTest instead Test, but UnityTest inherited from Test) and i cannot run fettle in the future :( or exists variant delegate run tests to unity (it can start from command line)?

**Comment by oliwennell** [comment]
It seems that at least one other person has encountered this error when trying to run NUnit against Unity3d tests. See last comments on these issues:
https://github.com/nunit/nunit/issues/2719
https://github.com/nunit/nunit-console/issues/345

(Fettle and the NUnit console both share the NUnit API code which seems to be throwing the exception).

The links above seem to suggest that a work-around may be to separate the "pure .NET" (POCO) code/tests from those that reference Unity3d.

Unfortunately I don't know Unity3d enough to say if there's a proper fix that can be made, so I'm gonna have to say that right now Fettle doesn't support Unity3d :(

**Comment by nsobiratel** [comment]
thank you for answer. i will try search bug reason. possible rework tests

**Comment by NikolayShitov** [comment]
Hi :) I do big work with our tests. Test project seperated on two part - one part run on device (Windows, Android, iOS, Mac, Uwp, Webgl) and generate data. Second part - console nunit application (self hosted custom runner) change some testing settings, do little environment setup and run tests - they validate generated data and receive some command line args. And now I want try use fettle. But could't - in config only assemblies, i cannot use custom runner. We can adopt fettle for my use case?

**Comment by oliwennell** [comment]
Hi @NikolayShitov 👋 

Thanks for the suggestion!

Right now Fettle works by using the NUnit API to run tests individually. This allows it to do optimisations, such as only running tests that are relevant to code being mutated or stopping test execution as soon as any test has failed.

If Fettle was to run the tests via an exe instead, it would not be able to apply these optimisations and run much more slowly. However, I can see how it could be useful to do this in some cases, so will create an issue to add it as a command-line option.

If you'd rather not wait, you should be able to set Fettle's `testAssemblies` configuration property to look at your custom test runner `exe`. However it would only work correctly if you changed your tests so that:
* The custom runner assembly contained all the tests that it ran.
* All setup was done via NUnit initialisation methods (e.g. `[OneTimeSetUp]` or `[SetUpFixture]` methods)

**Comment by oliwennell** [comment]
Created #52 for this

**Comment by oliwennell** [comment]
Version 0.5.0 introduced support for custom test runners.

If this doesn't work for you feel free to raise another issue @NikolayShitov
