### ISSUE TITLE
Structs with mutatable constructors are not supported

### ISSUE THREAD

**Issue by baccatabob** [ComparetheMarket/fettle#62]
There is a core dump if you try to use a struct that has a mutatable constructor such as

```
public struct MyStruct
{
    int minAllowed, maxAllowed;

    public MyStruct(int min, int max)
    {
        if (min > max) {throw new Exception("oh dear");}

        minAllowed = min;
        maxAllowed = max;
    }
}
```

The core dump happens in NUnitCoverageCollector::onTestComplete.  The member in memberIdsToNames that matches the key has a null value.

The cause of the null value is SyntaxNodeExtensions::NameOfContainingMember.  It starts with the parameter list for the struct's constructor, goes up a level and correctly finds a match for MemberDeclarationSyntax (because ConstructorDeclarationSyntax = grand-child of MemberDeclarationSyntax).  It goes up another level and fails.  It finds StructDeclarationSyntax rather than ClassDeclarationSyntax and they are peers rather than parent/child, so there is no match.  As the class hasn't been found, the method returns null, which is fed into memberIdsToNames.

**Comment by oliwennell** [comment]
Thanks for the report, never thought of that scenario.

I'll look to fix that soon.

**Comment by oliwennell** [comment]
Hey @baccatabob I've got a fix for this on `issue_62` branch.
It no longer crashes, and now properly mutates methods/properties within `struct`s.

If it helps, you should be able to build Fettle yourself from this branch and use that exe until I get the release together.

**Comment by baccatabob** [comment]
Thank you.  I'm not in a hurry for the fix, so I'll wait for the next release.

**Comment by baccatabob** [comment]
I'm too lazy to check the tests, but it just occurred to me that it's probably worth checking the other weird containers of methods - sealed, static, nested and abstract classes.  I expect that they'll all be fine, but a test is probably worth it.

**Comment by oliwennell** [comment]
Good shout, I'll look at the C# spec and see if there any other things like that will trip Fettle up

**Comment by baccatabob** [comment]
I'm sure that will be fun reading.  Maybe when you're having trouble sleeping...

**Comment by oliwennell** [comment]
So as far as I can tell, it should be ok.

In terms of the original crash, coverage analysis will now look within `struct`s and `class`es, and these seem to be the only things that can have "function members" (methods, properties, indexers, etc.).

That may change in C# 8 with default implementations of interface members (https://devblogs.microsoft.com/dotnet/building-c-8-0/) but that isn't out yet.

And for the rest of Fettle, it doesn't care what function members are contained within (it just looks for syntax nodes that correspond to methods, properties etc.), so it should be ok.
